# Generated by Django 2.1 on 2019-06-22 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, verbose_name='类目唯一标识')),
                ('address', models.CharField(max_length=255, verbose_name='类目地址')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='类目meta_title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='类目meta_description')),
                ('remark_title', models.TextField(blank=True, null=True, verbose_name='产品title_remark')),
                ('remark_description', models.TextField(blank=True, null=True, verbose_name='产品description_remark')),
                ('error_text', models.TextField(blank=True, null=True, verbose_name='发布错误信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seo_app.Store')),
            ],
            options={
                'db_table': 'collection',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('uuid', 'store')},
        ),
    ]
