# Generated by Django 2.1 on 2019-06-20 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0002_remove_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='seo_app.Store'),
            preserve_default=False,
        ),
    ]
