# Generated by Django 2.1 on 2019-06-25 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0002_auto_20190622_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='uri',
        ),
    ]
