# Generated by Django 2.1 on 2019-06-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0003_remove_store_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='uri',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='店铺唯一标示'),
        ),
    ]
