# Generated by Django 2.1 on 2019-06-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0003_product_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.SmallIntegerField(choices=[(-1, '333'), (0, '111'), (1, '222'), (2, '333')], default=0, verbose_name='产品状态'),
        ),
    ]
