# Generated by Django 2.1 on 2019-06-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0004_product_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='uri',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='店铺唯一标示'),
        ),
    ]
