# Generated by Django 2.1 on 2019-06-25 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0004_store_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='uri',
        ),
    ]
