# Generated by Django 2.1 on 2019-06-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0005_store_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.TextField(blank=True, null=True, verbose_name='产品缩略图'),
        ),
    ]
