# Generated by Django 2.1 on 2019-06-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0005_remove_store_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='money_format',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='店铺money标识'),
        ),
    ]
