# Generated by Django 2.1 on 2019-06-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0006_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.SmallIntegerField(choices=[(-1, '333'), (0, '111'), (1, '222'), (2, '333')], db_index=True, default=0, verbose_name='产品状态'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '111'), (1, '222'), (2, '333')], db_index=True, default=0, verbose_name='产品类型'),
        ),
    ]
