# Generated by Django 2.1 on 2019-07-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0006_store_money_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='产品描述'),
        ),
    ]
