# Generated by Django 2.1 on 2019-06-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0007_auto_20190620_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
