# Generated by Django 2.1 on 2019-07-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0007_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='产品描述'),
        ),
    ]
