# Generated by Django 2.1 on 2019-06-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0008_remove_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
