# Generated by Django 2.1 on 2019-06-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0009_remove_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.SmallIntegerField(choices=[(0, '新产品'), (1, '待发布'), (2, '已发布')], db_index=True, default=1, verbose_name='产品发布状态'),
        ),
    ]
