# Generated by Django 2.1 on 2019-06-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0010_auto_20190621_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='product',
            name='product_title',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='产品title'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='产品类型'),
        ),
    ]
