# Generated by Django 2.1 on 2019-06-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0012_auto_20190621_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='产品sku'),
        ),
    ]
