# Generated by Django 2.1 on 2019-07-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0012_auto_20190708_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='产品title'),
        ),
    ]
