# Generated by Django 2.1 on 2019-06-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0013_product_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='meta_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_title',
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(db_index=True, default=1, max_length=255, verbose_name='产品meta_title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='产品title'),
        ),
    ]
