# Generated by Django 2.1 on 2019-06-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0014_auto_20190621_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='产品价格'),
        ),
    ]
