# Generated by Django 2.1 on 2019-08-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0014_auto_20190809_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='collection_description',
            field=models.CharField(default='', max_length=255, verbose_name='collection_description'),
        ),
        migrations.AlterField(
            model_name='store',
            name='collection_title',
            field=models.CharField(default='', max_length=255, verbose_name='collection_title'),
        ),
        migrations.AlterField(
            model_name='store',
            name='product_description',
            field=models.CharField(default='', max_length=255, verbose_name='product_description'),
        ),
        migrations.AlterField(
            model_name='store',
            name='product_title',
            field=models.CharField(default='', max_length=255, verbose_name='product_title'),
        ),
    ]
