# Generated by Django 2.1 on 2019-06-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0015_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='产品meta_title'),
        ),
    ]
