# Generated by Django 2.1 on 2019-06-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0016_auto_20190621_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Variants',
            field=models.TextField(blank=True, null=True, verbose_name='产品variants'),
        ),
    ]
